[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "quickstats"
authors = [{name = "Alkaid Cheng", email = ""}]
dynamic = ["version", "description"]
